import "server-only";
// This file is auto-generated by amplify.yml during build in production.
// For local dev, it reads from process.env (populated by .env file).
export const AWS_CONFIG = {
  region: process.env.AWS_REGION || process.env.ADMIN_AWS_REGION || "us-east-1",
  accessKeyId: process.env.AWS_ACCESS_KEY_ID || process.env.ADMIN_AWS_ACCESS_KEY_ID || "",
  secretAccessKey: process.env.AWS_SECRET_ACCESS_KEY || process.env.ADMIN_AWS_SECRET_ACCESS_KEY || "",
  username: process.env.AWS_USERNAME || process.env.ADMIN_AWS_USERNAME || "",
} as const;
